eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: fornecedor
  datasource:
    password: postgres
    username: postgres
    url: 'jdbc:postgresql://localhost:5432/micro-service-fornecedor'
    driver-class-name: 'org.postgresql.Driver'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect 
